import { Figtree, Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const figtree = Figtree({ subsets: ['latin'], variable: '--font-sans' });

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

import { sprat } from '@/lib/fonts';
import { Toaster } from '@/components/ui/sonner';

export const metadata = {
  title: 'Interoperabilitas',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`scroll-smooth ${figtree.variable}`}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${sprat.variable} antialiased`}>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
